Robinjoon
baton-mission/java-boss-monster pull request #15
Opened 2023-10-04 18:21 UTC by robinjoon

우테코 최종 코테라고 생각하고 시간제한 걸어서 구현했습니다!!

처음에는 플레이어와 보스의 제약사항을 각각의 도메인 클래스의 생성자에 구현했었지만, 입력 오류 처리 과정에서 처음부터 다 다시 입력해야 하는 문제가 발생했습니다. 이를 해결하기 위해 아예 이러한 제약사항을 분리해 별도의 클래스로 정의하였습니다.

이러한 분리를 통해 다음과 같은 이점을 추가적으로 가져올 수 있었습니다.

> 변경이 잦을 수 있는 기본 정책을 핵심 도메인에서 분리해 유연성을 확보했습니다.

구현 중간에 입력과 출력을 담당하는 클래스를 따로 분리하는것이 메서드 길이나 깊이를 줄이기에 좋겠다는 생각이 들었고, 기능 목록에 이를 추가한 뒤 구현했습니다.

2023-10-04 18:49 UTC, robinjoon commented
GamePolicyException 클래스를 리팩토링과정에서 사용하지 않게 되었는데 삭제를 까먹었네요..ㅠㅠ
GameEndException 역시 리팩토링 하면서, 예외를 잡는 위치에서 누가 이겼는지 구분할 수 있어서, 내부의 필드를 사용하지 않는데 이것도 안바꿨구요..

2023-10-04 19:04 UTC, robinjoon commented
지금 보니까, 출력문구를 생성하는 걸 다른 클래스로 빼서 관리했다면 더 좋을거 같다 라는 생각이 드네요.

2023-10-05 01:35 UTC, cookienc requested changes
안녕하세요. 수빈 님:) 바톤팀의 에단입니다. 만나서 반갑습니다. 현재 서포터 선택이 완료되어 있지 않아 마이페이지 > 대기 중인 리뷰 > 서포터 선택을 저로 선택해 감사하겠습니다.🙇‍♂️🙇

코드 정상동작 하는 걸 확인했고, 구현 잘 해주셨습니다. 리뷰를 남겨놨으니 확인해 주시고 반영해 주시면 다시 리뷰해 드리겠습니다.

코드에 대한 개인적인 견해는 `추상화가 많이 되어있다.`는 점입니다. 모든 클래스마다 인터페이스가 붙어있는 구조인데 이렇게 만드신 이유가 있을까요? 수빈 님은 추상화를 언제 사용하는 게 좋다고 생각하시나요? 이에 대한 수빈 님의 생각이 궁금합니다! 또한, 5시간이라는 기준을 잡고 구현하셨다고 했는데, 제 경험상 무척 바빴을 것 같습니다. 아시다시피 [YAGNI](https://ko.wikipedia.org/wiki/YAGNI)의 원칙이란 게 있습니다. 현재 필요하지 않은 기능은 개발하지 않는다는 내용입니다. 확장성도 좋지만, 제한된 시간 안에서 그런 부분까지 고려하면서 코딩할 수 있을까요? 문의해 주신 아쉬운 점은 수빈 님 실력이면 시간만 있다면 충분히 개선할 수 있었을 것 같습니다. 제한 시간을 두셨다면 이런 부분을 고려해서 코드를 짜시면 더 좋은 개발자가 되실 것 같습니다.

아래는 궁금한 점에 대한 답변을 남겨놓았습니다. 


> 처음부터 어디까지 고려된 설계인지를 javadoc 나 README 등으로 남기는것이 좋을까요?

- 저는 설계에 대한 이유를 남기는 것은 좋은 방법이라고 생각합니다. 다만, 제가 생각하는 좋은 설계는 javadoc 같은 문서화를 하지 않아도 다른 개발자들이 이해할 수 있도록 설계하는 것이 좋은 설계라고 생각합니다. 만약 제가 수빈 님 입장이고, 현재 이 미션을 바탕으로 다른 개발자와 협업한다는 상황이라면 README에 기능 목록을 커밋을 할 때마다 `[ x ]` 체크 표시를 하는 방법이나, 아니면 PR 메시지에 설계 의도를 좀 더 알려주는 방향으로 진행했을 것 같습니다.

> 기능별로 커밋한다? 표현이 모호합니다. 제가 한 커밋중 일부는 기능별로 커밋을 했을것이고, 그렇지 않은 부분이 있을거 같은데 이에 대한 리뷰어님의 생각이 궁금합니다.

- `기능별로 커밋한다`라는 말에 너무 얽매여 있지 않으셔도 됩니다. 커밋을 사용하는 이유를 생각해 보시면 좋을 것 같아요. 개발자는 깃허브를 왜 사용할까요? 다른 개발자와 협업하기 위해서라는 이유도 있지만, 언제든지 롤백할 수 있다는 장점이 있습니다. 만약 서비스를 운영 중인데 새로운 기능을 개발하고 배포했더니 동작하지 않는다면, 이용자들은 불편하겠죠? 그럴 경우에는 빠르게 롤백해서 서비스를 정상화할 수 있습니다. 이런 이유를 생각해 보시면 어떨지 하는 생각으로`기능별로 커밋한다`라는 조건을 달았습니다. 추가로 롤백을 했는데 커밋이 제대로 동작을 안 한다면 당황스럽겠죠? 커밋을 할 때는 정상동작 하는 커밋을 올려주시면 더 좋습니다.


> 사용자 입력과 다음 입력 사이에 공백라인이 포함되어있는 것 같은 거요.

- 문서의 가독성을 위해서 그렇게 README에 작성해 놓았습니다. 공백이 있어서 서포터의 입장을 고려해주신 것 같아서 코드가 읽기 편했습니다😄. 만약 공백의 라인이 불필요하게 느껴진다면 어떠한 이유에서 불편했는지, 더 나은 방법은 없는지 생각해보는 것도 좋을것 같습니다.

> 이정도면 프리코스나 최종코테 못해서 떨어지지는 않겠죠..?

- 이 부분은 저희도 아는 바가 없어서 도움이 되질 못할것 같습니다. 죄송합니다ㅜㅜ

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +        }
scanner 객체가 의도치 않게 계속 생성되고 있네요.

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +public class InputProcessorByScanner implements InputProcessor {
InputProcessor로 추상화한 이유는 무엇인가요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/view/OutputProcessorBySystemOut.java
> +        System.out.println(String.format("[ERROR] %s",e.getMessage()));
```suggestion
        System.out.println(String.format("[ERROR] %s", e.getMessage()));
```
`String.format()` 사용 좋습니다👍👍  다만 띄어쓰기가 있었으면 좋겠어요

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/exception/GameEndException.java
> +    public GameEndException(String msg, boolean isPlayerWin) {
```suggestion
public class GameEndException extends RuntimeException {
    private final boolean playerWin;
    
    public GameEndException(String msg, boolean isPlayerWin) {
```
[구글컨벤션](https://google.github.io/styleguide/javaguide.html)을 참고해서 코드를 짜시면 더 좋은 코드가 될 것 같아요!

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/exception/GameEndException.java
> +    private final boolean playerWin;
예외가 상태를 가지고 있네요. 예외의 역할은 무엇일까요?🤔

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/Player.java
> +
개행이 두 줄이이에요!

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/Player.java
> +    abstract void attack(Boss boss, int value);
value가 무엇을 의미하나요? 더 좋은 이름이 없을까요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/PlayerImpl.java
> +class PlayerImpl extends Player {
Player는 어떤 이유로 추상화를 하셨나요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/PlayerImpl.java
> +        recoveryMp(10);
다른 개발자(or 한 달 뒤의 나)가 `recoveryMp(10)`을 보고 왜 10이 들어갔는지 다른 문서를 보지 않고선 이해하기 어려울것 같은데, 어떻게 개선시키면 좋을까요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/Boss.java
> +    }
도메인안에 view가 들어가 있네요 화면이 바뀌면 도메인도 같이 변경될거 같아요. 어떻게 개선시켜 볼 수 있을까요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/Player.java
> +    Player(String name, int hp, int mp) {
접근제어자 좋아요👍

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/Player.java
> +    }
<img width="231" alt="image" src="https://github.com/baton-mission/java-boss-monster/assets/83010167/c6cfd590-1b41-497b-a8f5-86b94ca372d9">

MP가 없어요!

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +        outputProcessor.print(String.format("\n마법공격을 했습니다. (입힌 데미지: %d)", 20));
마법 공격 데미지가 50으로 바뀐다면 두 개를 바꿔야하겠네요. 어떻게 하면 변경 영향을 줄일 수 있을까요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +        if (!canStart()){
[클린코드](https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29#understandability-tips)에서는 부정조건절을 지양해요

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/Player.java
> +    protected final String name;
protected로 선언한 이유가 있나요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +        if(attackType == 1){
attackType이 1이면 어떤 공격을 의미 할까요? 다른 개발자도 알 수 있게 변경해보는건 어떨까요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +    private int turnCount = 0;
GameEngine이 게임을 실행하는 역할과 턴의 수를 세는 역할을 동시에 하고 있네요. 분리해볼까요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +            }
처음 입력일 때는 예외처리를 안하기 위해서 이렇게 작성하셨다고 이해했습니다.
하지만 얼핏보면 두번째 입력부터 Error를 던지는 것처럼 보이는데요. try-catch를 사용해서 바꿔보는건 어떨까요?

2023-10-05 01:35 UTC, cookienc commented on src/main/java/bossmonster/domain/BasicRuleChecker.java
> +        }catch (Exception e){
split과 parseInt를 했을 때 발생하는 예외는 무엇일까요? Exception은 너무 포괄적인 느낌이 드네요

2023-10-05 01:44 UTC, robinjoon commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +        }
의도한 재생성 입니다. sc.nextInt() 호출 시점에 숫자가 아닌 다른 것을. 입력한 경우를 예외처리 하는 과정에서 scanner 객체를 재생성 하지 않고 다시 사용하는 경우 입력 버퍼문제때문인지 정상동작하지 않아서 위와같이 구현했습니다.

2023-10-05 01:46 UTC, robinjoon commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +public class InputProcessorByScanner implements InputProcessor {
처음에는 테스트코드 작성까지 고려하고 설계했습니다. 인터페이스로 추상화하면 mock 객체 생성해서 테스트할 수 있을 것으로 생각했기 때문입니다.

2023-10-05 01:47 UTC, robinjoon commented on src/main/java/bossmonster/view/OutputProcessorBySystemOut.java
> +        System.out.println(String.format("[ERROR] %s",e.getMessage()));
이런 컨벤션을 지켜본 적이 없어서 또 실수했네요.. 매번 확인해보고, ide 설정을 바꿔봐야 할 것 같습니다.

2023-10-05 01:53 UTC, robinjoon commented on src/main/java/bossmonster/domain/BasicRuleChecker.java
> +        }catch (Exception e){
음, 지금 보니 이 처리는 NumberFormatException 에 대한 예외만 잡는 걸로 해야겠네요. 정규식에 문제가 있어서 발생하는 예외는 애초에 코드에 오타가 있는 것이기 때문에 잡을 수 없는 예외이니까요.

2023-10-05 02:00 UTC, robinjoon commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +            }
예외를 투척 용도가 아니라, 예외 메세지 전달 용도로 사용했습니다. 말씀 주신 대로, 예외를 던지고 잡는 로직으로 구현하던지, 아니면 예외가 아니라 차라리 메세지를 직접 넘기는 방식으로 작성해야 할 것 같네요.

2023-10-05 02:01 UTC, robinjoon commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +        if(attackType == 1){
Enum 을 사용하는 방법이 있겠습니다.

2023-10-05 02:03 UTC, robinjoon commented on src/main/java/bossmonster/domain/Player.java
> +    protected final String name;
실수가 있었네요. 전혀 없습니다.

2023-10-05 02:08 UTC, robinjoon commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +        outputProcessor.print(String.format("\n마법공격을 했습니다. (입힌 데미지: %d)", 20));
가장 간단한 방법으로는 피해량을 별도의 로컬 변수로 빼는 방법이 있겠습니다. 하지만, 게임에서 피해량이란 자주 변경될 여지가 있는 부분이기 때문에 RuleChecker 에 피해량을 계산하는 책임을 이전시키는 방법이 더 나을 수도 있겠네요.
확장성을 극대화 하는 방법으로는 피해 라는 개념을 새로 추상화하는 방법이 있겠습니다.

2023-10-05 02:15 UTC, robinjoon commented on src/main/java/bossmonster/domain/Boss.java
> +    }
도메인을 아이콘으로 변환하는 책임을 분리해 다른 클래스로 이관하는 것도 좋은 방법이 되겠네요. 수정해보겠습니다.

2023-10-05 02:17 UTC, robinjoon commented on src/main/java/bossmonster/domain/PlayerImpl.java
> +        recoveryMp(10);
mp 회복량이나, 피해량 같은 것은 어찌보면 변할 수 있는 게임의 정책이 되겠네요. 게임의 밸런스와 관련된 수치들을 분리해서 다른 클래스로 이관하는 것이 더 나을 것 같습니다.

2023-10-05 02:19 UTC, robinjoon commented on src/main/java/bossmonster/domain/Player.java
> +    abstract void attack(Boss boss, int value);
공격력? 내지는 공격 강도? 와 같은 것으로 바꾸면 더 좋겠네요.

2023-10-05 02:30 UTC, robinjoon commented on src/main/java/bossmonster/domain/PlayerImpl.java
> +class PlayerImpl extends Player {
게임이라면, 언제나 새로운 종류의 캐릭터가 계속 등장하기 때문에 이를 반영하기 위한 의도였습니다. 하지만 막상 구현하고 보니 굳이 필요 없었을 수도 있겠다 싶긴 하네요.

2023-10-05 02:40 UTC, robinjoon commented
[YAGNI](https://ko.wikipedia.org/wiki/YAGNI) 원칙은 처음 들어본 말이네요. 의미 자체는 들어본적 있는거 같기도 하구요. 여러 책에서 인터페이스를 사용하는 것의 장점을 서술한 것들을 보고, 왠만한 것들은 인터페이스나 추상클래스를 두고 이를 구현하는 방향으로 설계하는 습관을 들였습니다. 개인적인 경험으로는 간혹 추상화로 인해 괜히 복잡성만 증가하는 경우도 있었지만, 추상화의 이점을 누릴 수 있는 경우가 더 많았습니다.

2023-10-05 13:51 UTC, cookienc commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +        }
`readLine`을 사용하면 객체를 재생성하지 않아도 됩니다

2023-10-05 13:53 UTC, cookienc commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +public class InputProcessorByScanner implements InputProcessor {
테스트를 위한 추상화를 하신다고 하셨는데, 테스트 코드가 비지니스 코드에 영향을 주는게 적당하다고 생각하시나요?

2023-10-05 13:56 UTC, cookienc commented
이번 보스몬스터 잡기를 하면서 추상화에 대한 이점을 누린적이 있나요? 어떤 점에서 장점을 느꼈나요?  추상화를 사용했을 때와 안했을 때 어떤 차이점이 있을까요?

2023-10-06 01:37 UTC, robinjoon commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +public class InputProcessorByScanner implements InputProcessor {
> 테스트를 위한 추상화를 하신다고 하셨는데, 테스트 코드가 비지니스 코드에 영향을 주는게 적당하다고 생각하시나요?

테스트코드가 직접적으로 비즈니스 코드에 영향을 주는 것은 당연히 적절하지 못합니다. 예를 들어, 
``` JAVA
class A{
    ...
    public static A getTestInstance(){
        return new A();
    }
}
```
위와 같이 테스트용 객체를 반환하는 메서드가 있는 것은 적절하지 못하다고 생각합니다. 하지만, 특정 클래스를 사용하는 다른 클래스의 정상작동 확인을 위한 테스트를 작성하기 위해 최초에 설계 시점에 인터페이스나 추상 클래스를 사용하는 것은 적절하다고 생각합니다. 물론 추상클래스나 인터페이스의 효과가 테스트를 용이하게 하는 것 뿐이 아니라, 관계가 복잡해질 수 있다는 단점을 포함해 많은 장단점이 있기 때문에 이를 적절히 고려해야 할 것입니다.

2023-10-06 01:43 UTC, robinjoon commented on src/main/java/bossmonster/exception/GameEndException.java
> +    private final boolean playerWin;
해당 예외는 게임이 종료되는 상황임을 전파하기 위해 사용합니다. 이 미션에서 게임의 종료에는 반드시 승패가 결정됩니다. 따라서, 게임이 종료 된 뒤 후처리를 하는 클래스에서 누가 게임을 이겼는지 쉽게 알게 하기 위해 필드를 추가했었습니다.
하지만, 구현 과정에서 예외를 처리하는 위치에 따라 승패를 완전히 추론할 수 있는 코드 구조가 되어 실질적으로 해당 필드를 사용하지 않았습니다.

즉, 현재 상황에선 제거 대상입니다. 다만, 예외가 내부 상태를 가지는 것이 아예 적절치 못한 것은 아니라고 생각합니다. 예외 역시 객체이고 객체가 내부에 상태를 가지는 것은 적절한 상태라면 가능한 것이기 때문입니다.

2023-10-06 01:52 UTC, robinjoon commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +    private int turnCount = 0;
게임엔진 도메인은 게임의 실행과 턴의 전환을 담당합니다. 게임 엔진은 외부로부터 게임 실행 메세지를 전달받으면 이를 수행합니다. 이 때 "턴" 이라는 개념 자체를 외부로 노출하고 있지 않은 만큼 "턴"은 게임 엔진 내부에서 관리되는 게임 엔진의 상태라고 생각합니다. 따라서 이를 다른 클래스로 분리하는 것 보다는 겡미 엔진이 직접 관리하도록 하는 것이 더 좋다고 생각합니다.

2023-10-06 02:03 UTC, robinjoon commented
> 이번 보스몬스터 잡기를 하면서 추상화에 대한 이점을 누린적이 있나요? 어떤 점에서 장점을 느끼셨나요? 추상화를 통해 얻은 장점이 항상 모든 코드에서 장점을 가져다 줄까요? 수빈님의 생각이 궁금합니다

이 미션을 최종 코딩테스트라 생각하고 수행했기 때문에 여러 추상화의 긍정적인 효과를 이루지 못했습니다. 추상화를 통해 얻을 수 있는 가장 큰 장점은 이후의 확장이 쉽다는 점입니다. 따라서, 단순히 이 미션에서 요구하는 기능만을 구현하기 위해서는 인터페이스나 추상 클래스를 이용한 추상화가 꼭 필요하지 않은게 맞는 것 같습니다.

결국 인터페이스나 추상클래스의 사용 여부는 그것이 얼마나 자주, 또 크게 변경될 것으로 생각하는지에 따라 결정해야 하는게 맞는 거 같습니다. 협업을 포함한 여러 경험이 쌓일 수록 그 예측의 정확도가 올라갈 것이라고 생각합니다. 그것이 우테코나 이런 코드리뷰를 통해 제가 얻고자 하는 것이기도 하구요.

2023-10-06 02:05 UTC, robinjoon commented
전체적으로 피드백 주신 내용들 반영해보고 싶은데, 이 PR에 강제로 커밋 하면 되는걸까요? 아니면 다시 PR 하나요?

2023-10-06 03:39 UTC, cookienc commented
로컬에서 푸시하시면 자동으로 pr이 업데이트 될거에요.

2023-10-08 19:13 UTC, robinjoon commented
피드백 주신 부분들 나름대로 수정해서 커밋했습니다. 점진적 추상화 영상 한번 봐야겠네요. 감사합니다!

2023-10-14 08:40 UTC, cookienc commented on src/main/java/bossmonster/view/InputProcessorByScanner.java
> +public class InputProcessorByScanner implements InputProcessor {
좋아요~ 실제로 작년 기수 체점하는 테스트 코드를 보면 Input을 mocking 하기 위해서 이런 느낌으로 구현을 했었는데요. 이 부분은 굳이 지금 신경쓰실 필요는 없을 것 같습니다

2023-10-14 09:40 UTC, cookienc approved these changes
안녕하세요 수빈님! 😄
리뷰 반영 잘 해주셨습니다! 이만 머지해도 될 것같아서 이번 미션에 대한 리뷰는 마치겠습니다. 
코멘트 남겨놨으니 고민해보셔도 좋을 것 같아요! 코드리뷰를 진행하면서 수빈님은 실력도 좋으시고, 코드를 짜신 이유가 명확해서 좋았습니다! 추가적으로 인텔리제이의 코드 포맷팅 기능을 사용한다면 더 읽기 좋은 코드가 될 것 같습니다.
바톤은 저희가 리뷰해주는 것도 있지만, 사용하시는 분들이 같이 코드리뷰를 통해서 학습하는 방향도 있으니 나중에 기회가 되셔서 사용해주시면 감사하겠습니다. 
마지막으로 바톤 홈페이지에서 리뷰 완료 메세지가 갈텐데 피드백 작성해주시면 감사하겠습니다! 고생하셨습니다.🙇‍♂️🙇

2023-10-14 09:40 UTC, cookienc commented on src/main/java/bossmonster/exception/GameEndException.java
> +    private final boolean playerWin;
`적절한 상태라면 가능한 것이기 때문`이 핵심인데요. 이 부분은 수빈님의 말씀이 맞습니다. 하지만 지금은 GameEndException이 예외를 던지면서 게임 로직을 컨트롤 하고 있기 때문에 적절한 상태도 아니고 적절한 예외도 아닙니다. 게임을 진행하다가 정상 종료되는게 예외인 상황일까요? 아니면 정상적으로 게임이 종료된 상황일까요? 이 부분에 대해서 고민하시면 좋을것 같아요

2023-10-14 09:40 UTC, cookienc commented on src/main/java/bossmonster/domain/BasicGameEngine.java
> +    private int turnCount = 0;
저는 게임엔진 도메인을 게임의 실행 역할로만 봤어요. 왜냐하면 충분히 그 역할만 해도 객체가 하는 역할이 많기 때문에요. BasicGameEngine이 변경될 여지가 크게 보았을 때 턴의 정책이 바뀌었을때, 게임 실행이 바뀌었을 때 두가지가 있는데요. 객체가 변경될 여지를 줄이는 것이 나중에 유지보수하기도 쉽기 때문에 추천드린거였습니다.

2023-10-14 09:40 UTC, merged