[보스 몬스터 잡기] 유선준 미션 제출합니다.
baton-mission/java-boss-monster pull request #5
Opened 2023-09-23 10:49 UTC by SeonJuuuun

안녕하세요 리뷰 해주셔서 감사합니다!

미션을 하면서 고민했던 점은 Controller에 메서드 수가 엄청 많아짐에 따라 Service 계층으로 로직을 분리해서 메서드 수를 줄이려고 생각을 했었습니다. 하지만 Service 로직에 있어야 할 코드의 기준을 모르겠더라구요 ㅠㅠ 😭

요즘은 InputView에 책임은 어디까지 일까에 대한 고민이 부쩍 늘었습니다 ㅠㅠ InputView에 기본적인 Blank값 같은 예외처리를 해주려고 하는데 어떤 분들은 예외 처리 책임을 분리 하기위해 InputValidator같은 클래스를 만들어서 사용을 하더라구요! 이에 대한 생각이 궁금합니다!

그리고 일반적인 객체로의 형 변환 책임은 Controller가 가져도 되는걸까요? 이를 서비스 계층에서 사용해도 될거 같은 생각이라 리뷰어님들의 생각이 궁금합니다!!

생각 보다 구현해야 할 기능들이 많았던거 같습니다! 실력도 많이 늘은거 같고 정말 좋은 기회 주셔서 감사합니다!!

2023-09-23 14:54 UTC, shin-mallang requested changes
안녕하세요 선준님~
미션 하시느라 고생하셨습니다~
코드 너무 잘 짜 주셔서 읽는데 불편함이 없었네요 :)
코멘트 조금 남겼으니 확인해주시고 의견 공유해주시면 감사하겠습니다:)

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/Main.java
> +	public static void main(String[] args) {
탭 설정이 조금 길게 된 것 같아요~
공백 4개만큼 길이로 조정해 주시면 감사하겠습니다 :)

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		play(bossMonster, player, count);
count는 굳이 전달하지 않아도 될 것 같아요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			AttackType type = repeat(() -> inputAttackType(player));
두 부분을 합치는 것은 어떨까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	private boolean checkPlayerHpZero(BossMonster bossMonster, Player player) {
메서드의 순서가 사용 순서대로 되어있으면 좀 더 읽기 편할 것 같아요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		if (player.playerHpZero()) {
playerHpZero보다는 isDead가 내부의 hp에 대한 캡슐화를 더 잘 지키면서, 죽었는지를 명확하게 표현할 수 있는 것 같아요~
지금 상태는 사실상 `player.hp == 0` 와 똑같다고 생각해요

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	}
check라는 naming을 가진 반면, 하는 행동은 check 이상의 행동을 하는 것 같아요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	}
BossMonster 객체를 조금 더 활용해보는건 어떨까요?
```java
BossMonster bossMonster = new BossMonster(hp, randomDamageGenerator);
```
```java
player.attackedBy(boss);
```
위와 같은 형태로요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	}
마찬가지로 Player를 더 잘 활용할 수 있을 것 같아요~
```suggestion
    private void attackBossByPlayer(BossMonster bossMonster, Player player, AttackType type) {
        player.attack(bossMonster, type);
    }
```

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		}
해당 검사를 attackBossByPlayer()에서도 진행해주고 있네요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		Health health = new Health(toInteger(bossHp));
이 부분도 InputView에서 정수를 바로 받아오도록 하면 좋을 것 같아요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			OutputView.printAttackType();
OutputView의 메서드 네이밍을 printAttackType로 짓는 순간부터 OutputView는 논리적으로 비즈니스 로직과 의존성을 갖게 된다고 생각합니다.
(공격 타입이라는 것을 View가 알고있는 것이니까요)

이런 상황에서 어떠한 문제점이 있을 수 있고, 또 그에 반해 어떠한 이점을 얻을 수 있는 구조인지 선준님의 생각이 궁금합니다!
(이 부분 뿐만 아니라 모든 Input, Output View에 대한 내용입니다.)

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			throw new IllegalArgumentException("[ERROR] 보스의 체력은 숫자만 입력이 가능합니다.");
toInteger의 예외처리 메세지가 toInteger와는 알맞지 않아 보여요! :)

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	private <T> T repeat(Supplier<T> inputReader) {
repeat만으로 어떤 상황에서, 언제까지, 몇번 반복하는지 알 수 있을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/AttackType.java
> +	PHYSICAL("1", 10, 10, "물리 공격"),
1과 2는 view와 관련된 값인데 도메인에서 이를 사용하고 있네요~
도메인이 뷰에 의존적이어도 괜찮을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/AttackType.java
> +	private final int effect;
effect가 무엇을 의미하는지 처음보는 사람이 명확하게 알 수 있을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/AttackType.java
> +	public static AttackType valueOfType(String type) {
마찬가지로 View에 의존적이네요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/BossMonster.java
> +	}
도메인 객체 내부에서, 관련 비즈니스 규칙을 검증해 주신 부분은 너무나 좋았습니다 👍
그런데 예외 메세지가 뷰에 의존적이네요~
이런 상황에서 어떠한 문제점이 발생할 수 있나요?
그리고 이를 어떻게 해결할 수 있을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/BossMonster.java
> +	}
위에서도 비슷한 말씀을 드렸는데, HP zero보다는 isDead가 더 명확하다고 생각합니다

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Health.java
> +	private static final int SUM_HP_MP = 200;
상수화 👍

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Health.java
> +		return hp < MIN_BOSS_HP || hp > MAX_BOSS_HP;
`MAX_BOSS_HP < hp || hp < MIN_BOSS_HP `
도 좋아 보입니다

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Health.java
> +	}
isHpZero는 단지 Hp가 Zero인지를 확인하는 부분인데, 이 부분에서 setHpZero를 해주는 것은 예상하지 못할 것 같아요~
이를 어떻게 해결할 수 있을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Health.java
> +	}
통일시킬 수 있는 좋은 방법은 없을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Health.java
> +	}
check 메서드 내에서 check만 수행하고 있지 않네요~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Player.java
> +	public boolean validateRemainMP(AttackType type) {
validate의 반환값을 통일해 주는 것이 어떨까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Player.java
> +			throw new IllegalArgumentException("[ERROR] 플레이어의 이름은 5자 이하만 가능합니다.");
마찬가지로 뷰와 의존적인 메세지입니다~

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Player.java
> +		if (name.length() > 5) {
Health에서는 상수값을 추출해 주셨는데 Player에서는 추출해주시지 않은 이유가 있으신가요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/RandomDamageGenerator.java
> +		Random random = new Random();
항상 Random 객체를 만들어 주어야 할까요~?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/domain/Health.java
> +	public boolean validateBossHpRange() {
Health가 Boss에 대해 알고 있는 것이 문제가 되지는 않을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/test/java/bossmonster/domain/HealthTest.java
> +	void validateBossHpRange_메서드는_보스의_피가_100이상_300이하가_되지않으면_true를_반환한다() {
이러한 테스트는 Health에는 어울리지 않는 것 같아요~
Health가 Boss의 비즈니스 규칙까지 가지고 있어서 이러한 문제가 발생한 것 같은데 어떻게 해결할 수 있을까요?

2023-09-23 14:54 UTC, shin-mallang commented on src/main/java/bossmonster/view/OutputView.java
> +	private static final String LINE_BREAK = "\n";
\n을 사용하는 것은 문제가 없을까요?
system.lineseparator()라는 것이 있는데 이에 대해 학습해 보시는 것도 좋을 것 같아요~

2023-09-23 15:41 UTC, SeonJuuuun reviewed
@shin-mallang 님 귀중한 리뷰 감사합니다!! 전혀 생각지도 못한 부분들을 짚어주셔서 오히려 더 소중한 리뷰였던거 같아요!! 감사합니다~~

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/Main.java
> +	public static void main(String[] args) {
앗 죄송합니다! 
초기 세팅할 때 문제가 있었나봐요! 감사합니다~~

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		play(bossMonster, player, count);
아! 그렇네요!! 리뷰 감사합니다~~

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	private boolean checkPlayerHpZero(BossMonster bossMonster, Player player) {
네! 감사합니다. 다음 부턴 꼭 적용하도록 할게요!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			OutputView.printAttackType();
헐 전혀 생각지도 못했네요 !
제 생각은 상대방에 읽기 좋게 AttackType을 출력하는 문구야~~ 라고 한 눈에 알아볼 수 있도록 짰는데
논리적으로 공격타입을 입력하면 뷰가 알게되는군요! 하나 크게 배워갑니다. 감사합니다!!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			AttackType type = repeat(() -> inputAttackType(player));
repeat 함수를 말씀하시는 걸까요??

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		if (player.playerHpZero()) {
아! 네이밍에 Hp라는문구가 들어가면 캡슐화에 위배 될 수도 있겠군요!! 감사합니다!!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	}
헉 이것도 설계할 때 생각도 못했던 내용이네요!
지금 와서 생각해보면, 보스가 데미지를 갖게 하는게 더 올바른 방향성이네요!!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	}
오.. 중간중간에 생각 나는 기능들을 끼워맞추다 보니 객체를 제대로 사용을 못했네요 ㅠㅠ 
좋은 지적 감사합니다!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		}
남아 있는 MP를 어떤 로직에 넣어야 될지 고민하다가 로직 하나를 못 지운거 같아요! 
완벽하다고 생각을 했는데 한번 더 보는 습관을 들여야겠어요 감사합니다!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +		Health health = new Health(toInteger(bossHp));
아! 그렇군요 프리코스처럼 하려다가 무의식적으로 Console.readLine() 을 생각해버렸어요! 감사합니다

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			throw new IllegalArgumentException("[ERROR] 보스의 체력은 숫자만 입력이 가능합니다.");
맞습니다 ㅠ 다른 좋은 방법을 생각해 보도록 할게요!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	private <T> T repeat(Supplier<T> inputReader) {
그 부분까진 생각하지 못했네요! 좀 더 수정해보도록 하겠습니다 감사합니다!!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/AttackType.java
> +	private final int effect;
그렇군요!! 네이밍에 더 신경쓰도록 하겠습니다! 감사합니다~~

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/AttackType.java
> +	PHYSICAL("1", 10, 10, "물리 공격"),
도메인은 뷰에 의존적이면 안된다고 생각합니다!
좀 더 설계에 신경쓰도록 하겠습니다 감사합니다!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/BossMonster.java
> +	}
네! 수정하겠습니다~ 감사합니다!!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Health.java
> +	private static final int SUM_HP_MP = 200;
감사합니다!!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Health.java
> +		return hp < MIN_BOSS_HP || hp > MAX_BOSS_HP;
감사합니다! 
MAX_BOSS_HP < hp < MIN_BOSS_HP
이런 느낌이라 훨씬 가독성에 좋을거 같아요!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Health.java
> +	public boolean validateBossHpRange() {
헐 맞네요 앞으로는 좀 더 깊게 생각하고 짜도록 하겠습니다! 감사합니다~~

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Health.java
> +	}
결국 같은 행동을 하는 메서드 군요! 좀 더 고민해보고 리뷰 남기도록 하겠습니다! 감사합니다~~

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Health.java
> +	}
이 부분에 대해 되게 고민이 많았어요!
메서드 분리를 한번 더 하면 좋을거 같긴한데 줄줄이 소세지 처럼 메서드가 작성될까봐 고치질 못했던거 같아요! 좋은 지적 감사합니다!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Player.java
> +		if (name.length() > 5) {
아.. 이것도 놓쳤군요.
 private static final int MAX_PLAYER_LENGTH = 5; 로 바꿀거 같습니다!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Player.java
> +			throw new IllegalArgumentException("[ERROR] 플레이어의 이름은 5자 이하만 가능합니다.");
감사합니다! 뷰에 의존적이지 않은 메세지로 변경해볼게요!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/Player.java
> +	public boolean validateRemainMP(AttackType type) {
감사합니다!!! isRemainMP이나 void 형식으로 맞추겠습니다!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/domain/RandomDamageGenerator.java
> +		Random random = new Random();
@shin-mallang 님이 말씀 해주신것처럼 BossMonster에서 사용할 수 있는 방법을 찾아보겠습니다! 감사합니다!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/main/java/bossmonster/view/OutputView.java
> +	private static final String LINE_BREAK = "\n";
좋은 키워드 감사합니다!! 학습해 보도록 할게요!!

2023-09-23 15:41 UTC, SeonJuuuun commented on src/test/java/bossmonster/domain/HealthTest.java
> +	void validateBossHpRange_메서드는_보스의_피가_100이상_300이하가_되지않으면_true를_반환한다() {
Health에서 Boss나 Player의 로직을 제거하고 단지, 사용할 수 있게만 하는 방향성으로 할 거 같습니다! 감사합니다!

2023-09-23 15:46 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			AttackType type = repeat(() -> inputAttackType(player));
printAttackType 내에서 공격 타입을 선택해주세요와 같은 메세지를 함께 출력하는 것을 의미했습니다 :)

2023-09-23 15:47 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	private boolean checkPlayerHpZero(BossMonster bossMonster, Player player) {
수정하시고 커밋하면 해당 PR에 자동으로 추가되니 고친 이후 추가적으로 리뷰 받으시고 싶으시면 반영한 뒤 말씀해 주시면 추가적으로 리뷰 해드릴게요!

2023-09-23 15:49 UTC, shin-mallang commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			throw new IllegalArgumentException("[ERROR] 보스의 체력은 숫자만 입력이 가능합니다.");
고민해보시고 반영해서 커밋해주시면 확인하겠습니다 :)

2023-09-23 15:51 UTC, shin-mallang commented on src/test/java/bossmonster/domain/HealthTest.java
> +	void validateBossHpRange_메서드는_보스의_피가_100이상_300이하가_되지않으면_true를_반환한다() {
그렇다면 `보스의_피가_100이상_300이하가_되지않으면_true를_반환한다` 라는 테스트는 어디에서 진행하면 좋을까요~?

2023-09-23 16:12 UTC, SeonJuuuun commented
>안녕하세요! 말랑님! 귀중한 리뷰 잘봤습니다!!
>미처 생각 못했던 부분을 긁어주셔서 정말 감사합니다!!
>
>
>첫번째 질문에 대한 답변 드릴게요!
>
>제가 생각하는 Service는 2번과 같은거 였어요! 
>제가 Service계층을 만들려고 하는 이유가 Controller에 메서드가 너무 많아 가독성을 해칠까봐 였고, 
>컨트롤러와 도메인 사이에 Service 계층을 만들어 중간 다리 역할을 하면 가독성도 좋고 
>컨트롤러가 뷰와 도메인을 연결시키는데 더 도움이 되지 않을까 싶어서요!
>
>하지만 말랑님이 보시는데 불편함이 없었다면, Service가 필요 없을거 같긴 해요!
>근데 제가 보기에 Controller에 모든 로직이 있으면 너무 복잡하게 보여 책임 분산을 위해 Service를 만들어
>분산해 볼 생각은 있습니다! 
>이 부분은 지금 당장 이렇게 해야겠다! 가 아니라 좀 더 코드를 작성해보면서 저에게 맞는 방법을 찾아가 보도록 하겠습니다!!
>정말 감사드립니다 말랑님!!
>
>궁금한게 있는데 혹시 
> ```java
> public Player createPlayer(String name) {
>     return new Player(name);
> }
> ```
>이 부분은 서비스에 작성을 하신건가요!?!?
>
>

>
>두번째 질문에 답변을 제가 너무 애매하게 질문 한거 같아요! 죄송합니다 ㅠㅠ
>
>제가 말씀드린건 도메인 규칙 말고 값이 정수인지 Blank인지 입력에 대한 예외 사항들을 말한거에요!
>
>지금 당장은 프로그램이 작아서 InputView에 메서드 형태로 넣어도 된다고 생각하지만, 
>만약 프로그램이 커지면 입력에 대한 예외도 많아 질거라는 생각에 InputValidator를 생각했던거 같아요!
>InputValidator를 사용하면 InputView에 예외 처리에 대한 책임이 InputValidator로 분리가 되고 예외 사항을
>한 눈에 알아볼 수 있다는 반면에 
>InputView는 클래스 내에서 메서드를 만드니까 다른 의존성이 없다는게 장점같아요!
>
>작은 프로그램은 클래스 내 메서드 형태로 만들고, 큰 프로그램은 InputValidator라는 클래스를 만들어서 관리한다면
>뭔가 통일성이 없다고 느껴서 저만의 방법을 찾기 위해 질문했습니다 ㅠㅠ 
>

>세번째 질문에 대한 답변 드릴게요!
>
>1. Controller와 Service의 책임을 어떻게 정의하고 사용하고 계신가요?
>=> 1번 질문에서도 말씀 드렸듯이, Controller는 뷰와 도메인을 연결을 시키는 역할로 보고
>Service는 형 변환과 "," 같은 요구사항에 분리를 시켜주는 역할Controller와 domain 사이에서 비즈니스 로직을
>수행하는 책임이 있다고 생각합니다! 
>
>
>2. Controller에서 일반적인 객체로 형 변환을 하면 어떠한 장단점이 있을까요?
>=> 음.. 이거에 대해선 좀 더 고민해봐야 할거 같아요.
>이유가 있어서 넣은게 아니라 Service가 없다면 넣을 곳이 Controller 밖에 없다고 해서 넣었습니다
>
>
>3. Service 계층에서 형 변환을 진행하면 어떠한 장단점이 있을까요?
>=> 형 변환 같은 경우에는 유틸성이 강하다는 느낌이 들어서 이를 Service 계층으로 책임을 전가하면
> Controller에 있는 책임을 분산시킬수 있다고 생각합니다!
>
>
>뭔가 이렇게 답변을 하다보니 Service 계층을 도입해야 할거 같은 느낌이 드네요 ㅋㅋㅋ

2023-09-23 16:14 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +			AttackType type = repeat(() -> inputAttackType(player));
아하!! 감사합니다!! 그렇게 하면 좀 더 간결하겠군요!

2023-09-23 16:15 UTC, SeonJuuuun commented on src/main/java/bossmonster/controller/BossMonsterGame.java
> +	private boolean checkPlayerHpZero(BossMonster bossMonster, Player player) {
헉.. 바쁘실텐데 정말 감사합니다!

2023-09-23 16:16 UTC, SeonJuuuun commented on src/test/java/bossmonster/domain/HealthTest.java
> +	void validateBossHpRange_메서드는_보스의_피가_100이상_300이하가_되지않으면_true를_반환한다() {
보스의 HP는 BossMonster가 가지고 있기 때문에 BossMonster에서 해야 한다고 생각합니다!

2023-09-23 16:19 UTC, SeonJuuuun commented on src/test/java/bossmonster/domain/HealthTest.java
> +	void validateBossHpRange_메서드는_보스의_피가_100이상_300이하가_되지않으면_true를_반환한다() {
보스의 HP는 BossMonster에서 가지고 있으니 BossMonsterTest에서 해야 할거 같습니다!

2023-09-23 16:42 UTC, shin-mallang commented
>궁금한게 있는데 혹시
```java
public Player createPlayer(String name) {
    return new Player(name);
}
이 부분은 서비스에 작성을 하신건가요!?!?
```
네 맞습니당 :)

---

> 작은 프로그램은 클래스 내 메서드 형태로 만들고, 큰 프로그램은 InputValidator라는 클래스를 만들어서 관리한다면
뭔가 통일성이 없다고 느껴서 저만의 방법을 찾기 위해 질문했습니다 ㅠㅠ
프로그램의 규모의 따라 구조가 달라지는 것은 당연하다고 생각해요 :)
통일성은 하나의 프로그램 내에서 지켜지면 되는 것이지 현재 프로그램과 미래의 프로그램 사이에서 지켜질 필요는 없을 것 같습니다 :)

정수인지 Blank인지 등, 입력에 대한 예외가 한정적이므로 프로그램 규모가 커지더라도 추가되거나 확장되지는 않을 것 같아요!

잘 고민해보시고 선택하시면 좋을 것 같습니다. :)

---
> => 1번 질문에서도 말씀 드렸듯이, Controller는 뷰와 도메인을 연결을 시키는 역할로 보고
Service는 형 변환과 "," 같은 요구사항에 분리를 시켜주는 역할Controller와 domain 사이에서 비즈니스 로직을
수행하는 책임이 있다고 생각합니다!

뷰와 도메인을 연결시키는 역할이라면 `"," 같은 요구사항에 분리를 시켜주는 역할` 역시도 Controller에 있어야 하지 않을까요?
,를 통해 구분하여 입력받는 것은 뷰의 규칙이지 비즈니스 규칙은 아닌 것 같아요~


> => 형 변환 같은 경우에는 유틸성이 강하다는 느낌이 들어서 이를 Service 계층으로 책임을 전가하면
Controller에 있는 책임을 분산시킬수 있다고 생각합니다!

그렇다면 하나의 컨트롤러에서 여러 서비스를 사용하는 상황을 가정해볼까요?
이러한 상황에서 서비스에서 형 변환을 처리해주면 어떤 문제가 발생할 수 있을까요?

2023-09-24 08:30 UTC, SeonJuuuun commented
> 뷰와 도메인을 연결시키는 역할이라면 `"," 같은 요구사항에 분리를 시켜주는 역할` 역시도 Controller에 있어야 하지 않을까요? ,를 통해 구분하여 입력받는 것은 뷰의 규칙이지 비즈니스 규칙은 아닌 것 같아요~
>
그렇군요! 뷰의 규칙으로 볼 수도 있겠네요! 그러면 입력에 대한 책임으로 봐서 InputView에 넣어도 될까요?
사실.. 이미 고민한 결과 InputView에 넣어도 된다고 결정을 내렸는데 확인 한번 하면 마음이 편할거 같아서요 😭
> 
> > => 형 변환 같은 경우에는 유틸성이 강하다는 느낌이 들어서 이를 Service 계층으로 책임을 전가하면
> > Controller에 있는 책임을 분산시킬수 있다고 생각합니다!
> 
> 그렇다면 하나의 컨트롤러에서 여러 서비스를 사용하는 상황을 가정해볼까요? 이러한 상황에서 서비스에서 형 변환을 처리해주면 어떤 문제가 발생할 수 있을까요?
>
컨트롤러 안에 많은 서비스의 의존성이 생길거 같습니다! 고민해본 결과 제가 생각한 방향은 InputView에선 간단한 `,` 분리와 기본 타입들로의 변환정도의 책임은 괜찮다고 생각이 드네요! 
그렇게 생각한 이유는, 
1. 기존에는 이름들을 `,` 를 기준으로 분리해서 입력받았는데, 구분자가 `/` 로 변경되었다고 가정해보면,
이는 입력을 받는 형식, 즉 InputView에서의 변화인데 파싱을 다른 곳에서 진행하면 그 곳까지 변화의 영향을 받을 수 있을거 같다고 생각이 들어서요!
2. 기본 타입들로의 변환은 기본적으로 Java안에 내장되어 있는 타입들이므로 도메인 객체를 아는게 아니라 상관없을거 같아요!

그리고 domain 형태의 형 변환은 Controller가 하는게 맞다고 생각이 듭니다! 왜냐하면 Controller의 역할은 View와 Domain을 연결 시켜주는 역할이므로 정보를 알고 있는 Controller가 해야 한다고 생각하기 때문입니다. 😄

2023-09-26 10:49 UTC, shin-mallang commented
> 그렇군요! 뷰의 규칙으로 볼 수도 있겠네요! 그러면 입력에 대한 책임으로 봐서 InputView에 넣어도 될까요?
사실.. 이미 고민한 결과 InputView에 넣어도 된다고 결정을 내렸는데 확인 한번 하면 마음이 편할거 같아서요 😭

선택에 이유가 있으시다면, 그것만으로 써도 되지 않을까 싶네요:)
(저는 두 방법 모두 괜찮다고 생각합니다 :))

> 컨트롤러 안에 많은 서비스의 의존성이 생길거 같습니다! 

일반적으로 컨트롤러는 서비스보다 상위 계층에 속하므로 여러 서비스를 사용하는 것은 문제가 없습니다:)
제 의도는 여러 서비스에서 형 변환을 처리해주기 위한 코드가 중복되는 문제를 인지하는 것이었습니다😊

> 고민해본 결과 제가 생각한 방향은 InputView에선 간단한 , 분리와 기본 타입들로의 변환정도의 책임은 괜찮다고 생각이 드네요!
그렇게 생각한 이유는,

기존에는 이름들을 , 를 기준으로 분리해서 입력받았는데, 구분자가 / 로 변경되었다고 가정해보면,
이는 입력을 받는 형식, 즉 InputView에서의 변화인데 파싱을 다른 곳에서 진행하면 그 곳까지 변화의 영향을 받을 수 있을거 같다고 생각이 들어서요!
기본 타입들로의 변환은 기본적으로 Java안에 내장되어 있는 타입들이므로 도메인 객체를 아는게 아니라 상관없을거 같아요!

👍


> 그리고 domain 형태의 형 변환은 Controller가 하는게 맞다고 생각이 듭니다! 왜냐하면 Controller의 역할은 View와 Domain을 연결 시켜주는 역할이므로 정보를 알고 있는 Controller가 해야 한다고 생각하기 때문입니다. 😄

좋은 것 같습니다!👍
지금의 생각을 모든 상황에 일관되게 적용하려고 하는 것만 주의하시면 좋을 것 같아요!
나중에 중간 계층(ex: service)이 추가되거나 구조가 아예 바뀌는 경우에, 상황마다 적절한 위치가 다를 수 있으니 항상 이를 고민하시고 코드를 작성하시면 좋을 것 같아요:)

2023-09-27 06:04 UTC, SeonJuuuun commented
감사합니다 말랑! 많은 도움 됐어요!! 말씀하신거 꼭 유의 할게요!

2023-12-27 03:32 UTC, closed without merging